# encoding: utf-8
# Site settings
title: Andrzej Jóźwiak - Blog
author: Andrzej Jóźwiak
description: My blog about software design, programming and all this stuff...
baseurl:
url: http://ajoz.github.io

customsearch: 009777578059784488631:8kibs8jmyma

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

permalink: pretty
highlighter: rouge

kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: public/css
  style: :compressed

gems:
  - jekyll-sitemap
